name: CI/CD for Angular

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Build Angular app
        run: npm run build --if-present

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/angular-app:v0.4 .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/angular-app:v0.4

      - name: Checkout manifests repository
        uses: actions/checkout@v2
        with:
          repository: store-Db/manifest
          path: manifests

      - name: Update manifest
        run: |
          ls -l  manifests/work  # Check if the directory exists and list its contents
          sed -i 's#image: .*$#image: '"${{ secrets.DOCKER_HUB_USERNAME }}/angular-app:v0.4"'#g' manifests/work/front.yaml

      - name: Commit and push changes
        run: |
          cd manifests
          git config --global user.email "bentarjem.sara@esprit.tn"
          git config --global user.name "sara-8"
          git add .
          git commit -m "Update Angular app image to v0.4"
          git push https://store-Db:${{ secrets.PAT_GITHUB }}@github.com/store-Db/manifest.git HEAD:main
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_GITHUB }}
